#!/bin/bash

grep -oE '^(([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))\.){3}([1-9]?[0-9]|1[0-9][0-9]|2([0-4][0-9]|5[0-5]))' nginx-access.log | uniq -c | sort -hr | head -n 5 >> listIps.txt

while read line; do

requests=$(echo $line | awk '{print $1}')
ip=$(echo $line | awk '{print $2}')

	echo 'The: '${ip}' - has '${requests}' requests'

done < listIps.txt

rm listIps.txt
